version: '3.8'
services:
  tenant-service:
    build: .
    environment:
      - AUTH_MS_URL=http://auth-service:8000
      - DB_HOST=tenant-db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8003:8003"
    depends_on:
      - tenant-db
    networks:
      - tenant-internal
      - microservices-bridge
      
  tenant-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    networks:
      - tenant-internal
    
networks:
  tenant-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true
