version: '3.8'
services:
  tenant-service:
    build: .
    environment:
      - AUTH_MS_URL=http://auth-service:8000
      - DB_HOST=tenant-db
      - DB_PORT=5432
      - REDIS_URL=redis://tenant-redis:6379
    ports:
      - "8003:8003"
    depends_on:
      - tenant-db
      - tenant-redis
    networks:
      - tenant-internal
      - microservices-bridge
      
  tenant-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    networks:
      - tenant-internal
    
  tenant-redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    networks:
      - tenant-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
networks:
  tenant-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true
