version: '3.8'

services:
  # Node.js application service
  product-service:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://auth-service:8000
      - TENANT_MS_URL=http://tenant-service:8003
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8002:8002"
    depends_on:
      - db
      - redis
    networks:
      - product-network
      - auth-network


  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    networks:
      - product-network

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]  # Disabled protected mode
    networks:
      - product-network  # Added network for redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  
networks:
  product-network:
    driver: bridge
  auth-network:
    name: shared-microservices-network
    external: true
