version: '3.8'

services:
  # Node.js application service
  product-service:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://auth-service:8000
      - TENANT_MS_URL=http://tenant-service:8003
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8002:8002"
    depends_on:
      - db
    networks:
      - product-internal
      - microservices-bridge

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - product-internal

networks:
  product-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true

