---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-auth
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-auth.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "authentication"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-auth
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-auth-db
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-auth.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "authentication"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-auth-db
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:latest
        command: ['sh', '-c', 
          'until pg_isready -h database-auth.backend-aaw.svc.cluster.local -p 5432 -U postgres; do echo "Waiting for database"; sleep 2; done;']
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets-auth
              key: DB_PASSWORD

      containers:
      - name: authentication
        image: gnh374/authentication:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config-auth
        - secretRef:
            name: app-secrets-auth
        volumeMounts:
        - name: auth-storage
          mountPath: /app/data
        resources:
          requests:
            cpu: "250m"  # 0.1 core
            memory: "256Mi"
          limits:
            cpu: "500m"  # 0.2 core
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
           
      volumes:
      - name: auth-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: backend-aaw
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 8000
    nodePort: 30000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-auth
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-auth
  template:
    metadata:
      labels:
        app: database-auth
    spec:
      containers:
      - name: database-auth
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config-auth
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets-auth
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets-auth
              key: DB_PASSWORD

        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: authentication-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database-auth
  namespace: backend-aaw
spec:
  type: ClusterIP
  selector:
    app: database-auth
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentication-pv
  namespace: backend-aaw
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/authentication"  # Changed to a more accessible local path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-pvc
  namespace: backend-aaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-hpa
  namespace: backend-aaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
