---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-orders.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "orders"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: gnh374/orders:latest
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: orders-storage
          mountPath: /app/data
        resources:
          requests:
            cpu: "100m"  # 0.1 core
            memory: "256Mi"
          limits:
            cpu: "200m"  # 0.2 core
            memory: "512Mi"
      volumes:
      - name: orders-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: backend-aaw
spec:
  type: NodePort
  selector:
    app: orders
  ports:
  - protocol: TCP
    port:  30001
    targetPort: 8001
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-orders
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-orders
  template:
    metadata:
      labels:
        app: database-orders
    spec:
      containers:
      - name: database-orders
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD

        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: database-orders
  namespace: backend-aaw
spec:
  type: ClusterIP
  selector:
    app: database-orders
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-pv
  namespace: backend-aaw
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/orders

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-pvc
  namespace: backend-aaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-hpa
  namespace: backend-aaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75


