---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-products
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-products.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "products"
  AUTH_MS_URL: "http://authentication.backend-aaw.svc.cluster.local:30000"
  TENANT_MS_URL: "http://tenants.backend-aaw.svc.cluster.local:30003"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-product
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-products-db
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-products.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "products"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-product-db
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup database-products.backend-aaw.svc.cluster.local && nc -z database-products.backend-aaw.svc.cluster.local 5432; do echo "Waiting for database"; sleep 2; done;']
      - name: wait-for-auth
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup authentication.backend-aaw.svc.cluster.local && nc -z authentication.backend-aaw.svc.cluster.local 30000; do echo "Waiting for auth service"; sleep 2; done;']
      containers:
      - name: products
        image: gnh374/products:latest
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: app-config-products
        - secretRef:
            name: app-secrets-product
        volumeMounts:
        - name: products-storage
          mountPath: /data
        resources:
          requests:
            cpu: "250m"  # 0.1 core
            memory: "256Mi"
          limits:
            cpu: "500m"  # 0.2 core
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 5
           
      volumes:
      - name: products-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: backend-aaw
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 30002
    targetPort: 8002
    nodePort: 30002


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-products
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-products
  template:
    metadata:
      labels:
        app: database-products
    spec:
      containers:
      - name: database-products
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config-products
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets-product
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets-product
              key: DB_PASSWORD

        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: products-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database-products
  namespace: backend-aaw
spec:
  type: ClusterIP
  selector:
    app: database-products
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-pv
  namespace: backend-aaw
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/products

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-pvc
  namespace: backend-aaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-hpa
  namespace: backend-aaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50


