---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-tenants.database-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "tenants"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"
  AUTH_URL: "http://authentication.backend-aaw.svc.cluster.local:30000/api"
  TENANT_URL: "http://tenants.tenants.svc.cluster.local:30003/api"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants
  namespace: backend-aaw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenants
  template:
    metadata:
      labels:
        app: tenants
    spec:
      containers:
      - name: tenants
        image: tenants:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: tenants
  namespace: backend-aaw
spec:
  type: NodePort
  selector:
    app: tenants
  ports:
  - protocol: TCP
    port:  30003
    targetPort: 8003
    nodePort: 30003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-tenants
  namespace: database-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-tenants
  template:
    metadata:
      labels:
        app: database-tenants
    spec:
      containers:
      - name: database-tenants
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD

        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: tenants-storage
        persistentVolumeClaim:
          claimName: tenants-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database-tenants
  namespace: database-aaw
spec:
  type: ClusterIP
  selector:
    app: database-tenants
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenants-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/tenants

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenants-pvc
  namespace: database-aaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
