---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-wishlists.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "wishlists"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"
  AUTH_MS_URL: "http://authentication.backend-aaw.svc.cluster.local:30000"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-db
  namespace: backend-aaw
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  ADMIN_TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "database-wishlists.backend-aaw.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "wishlists"
  PRODUCT_MS_URL: "http://products.backend-aaw.svc.cluster.local:30002/api"
  REDIS_URL: "redis://redis.backend-aaw.svc.cluster.local:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-db
  namespace: backend-aaw
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc2p3dF9zZWNyZXQ="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlists
  namespace: backend-aaw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlists
  template:
    metadata:
      labels:
        app: wishlists
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:latest
        command: ['sh', '-c', 'until pg_isready -h database-wishlists.backend-aaw.svc.cluster.local -p 5432 -U postgres; do echo "Waiting for database"; sleep 2; done;']
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
      - name: wait-for-auth
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup authentication.backend-aaw.svc.cluster.local && nc -z authentication.backend-aaw.svc.cluster.local 30000; do echo "Waiting for auth service"; sleep 2; done;']
      - name: wait-for-redis
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup redis.backend-aaw.svc.cluster.local && nc -z redis.backend-aaw.svc.cluster.local 6379; do echo "Waiting for Redis"; sleep 2; done;']
      containers:
      - name: wishlists
        image: gnh374/wishlists:latest
        ports:
        - containerPort: 8004
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            cpu: "200m"  # 0.1 core
            memory: "256Mi"
          limits:
            cpu: "200m"  # 0.2 core
            memory: "512Mi"
        volumeMounts:
        - name: wishlists-storage
          mountPath: /data
        startupProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: wishlists-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: wishlists
  namespace: backend-aaw
spec:
  type: NodePort
  selector:
    app: wishlists
  ports:
  - protocol: TCP
    port:  30004
    targetPort: 8004
    nodePort: 30004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-wishlists
  namespace: backend-aaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-wishlists
  template:
    metadata:
      labels:
        app: database-wishlists
    spec:
      containers:
      - name: database-wishlists
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD

        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: wishlists-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database-wishlists
  namespace: backend-aaw
spec:
  type: ClusterIP
  selector:
    app: database-wishlists
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wishlists-pv
  namespace: backend-aaw
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/wishlists

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlists-pvc
  namespace: backend-aaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wishlists-hpa
  namespace: backend-aaw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wishlists
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50


