version: '3.8'

services:
  # Node.js application service
  wishlist-service:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://auth-service:8000
      - DB_HOST=wishlist-db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8004:8004"
    depends_on:
      - wishlist-db
    networks:
      - wishlist-internal
      - microservices-bridge

  # PostgreSQL database service
  wishlist-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5429:5432"
    networks:
      - wishlist-internal

networks:
  wishlist-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true
