version: '3.8'
services:
  order-service:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://auth-service:8000
      - DB_HOST=order-db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "8004:8001"
    depends_on:
      - order-db
    networks:
      - order-internal
      - microservices-bridge
      
  order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    networks:
      - order-internal
  
networks:
  order-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true

