version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=auth_ms_jwt_secret
      - DB_HOST=auth-db
      - DB_PORT=5432
      - REDIS_URL=redis://auth-redis:6379
    depends_on:
      - auth-db
      - auth-redis
    networks:
      - auth-internal
      - microservices-bridge
      
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - auth-internal
    
  auth-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    networks:
      - auth-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
networks:
  auth-internal:
    driver: bridge
  microservices-bridge:
    name: microservices-bridge
    driver: bridge

