version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "no", "--save", "" , "--protected-mode", "no"]
    networks:
      - microservices-bridge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  
networks:
  microservices-bridge:
    name: microservices-bridge
    driver: bridge
    external: true


